path: /home/kaustubh/Codes/rov_object_detection/yolov8_testing

# Dataset structure
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')


# Number of classes
nc: 1


# Class names
names:
 0: BlueROV2